### ISSUE TITLE
Blood floats in air after it sticks to moving walls

### ISSUE THREAD

**Issue by Someone65** [JRHard771/droplets#2]
This is a thing that can happen... ![floating blood](https://vgy.me/j9CwIA.png)

Did this using the latest version of droplets as of 10/16/2018 (not the latest release, the latest commit)
You can see this happening in Doom 2 MAP02 where lots of cloaked Pinkies reside.

**Comment by caligari87** [comment]
This is a known issue, actually. Josh is working on ways to have the decals stick to moving walls.

**Comment by caligari87** [comment]
Was this fixed in the latest release? If so I think it can be closed.

**Comment by JRHard771** [comment]
Oh, I should _really_ learn to check whether I have any submitted issues... heh.

Yeah, this has been long fixed as of right now, so I'm closing the issue. I appreciate that you submitted the issue, though.
